# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

# CI项目
name: CWRT-全平台编译

# CI计划
on:
  # 自动编译：每周一早上5点
  schedule:
    - cron: 0 21 * * 0
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用换行符隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# CI权限
permissions: write-all

# CI任务
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 删除旧的 Releases 和工作流
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0

  config:
    needs: cleanup
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [MT7981, MT7986]
        REPO_INFO:
          - {SOURCE: "padavanonly/immortalwrt-mt798x-6.6", BRANCH: "openwrt-24.10-6.6"}

    uses: ./.github/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{matrix.CONFIG}}
      WRT_DEVICE: ""
      WRT_THEME: aurora
      WRT_NAME: WR30U
      WRT_SSID: CMCC-7920
      WRT_WORD: 123456789
      WRT_IP: 192.168.1.2
      WRT_PW: 无
      WRT_REPO: https://github.com/${{matrix.REPO_INFO.SOURCE}}.git
      WRT_BRANCH: ${{matrix.REPO_INFO.BRANCH}}
      WRT_SOURCE: ${{matrix.REPO_INFO.SOURCE}}
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      WRT_TEST: ${{inputs.TEST || false}}